# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Install pandas and numpy if the active Python environment does not have them. Using Python venv is recommended when you are doing so.
%pip install pandas numpy

Requirement already satisfied: pandas in c:\users\omarx\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\omarx\appdata\local\programs\python\python312\lib\site-packages (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\omarx\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\omarx\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\omarx\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\omarx\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

Load the Food choices data set into a new variable, `df_food`.

In [3]:
# Load the Food choices data set.

food_data_set_path = 'data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

In [5]:
# Try to print or display it nicely.
df_food.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

What are the columns and their types in this data set?

In [6]:
# Show the column names and their types.
df_food.columns
df_food.dtypes

GPA                  object
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports          object
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight               object
Length: 61, dtype: object

In [7]:
pd.set_option("display.max_rows", 100) # Set pandas to render up to 100 rows first. Default caps to 10 and takes the middle chunk out to make the DataFrame fit.

# Try to display the column information as a nice pandas DataFrame.
pd.DataFrame({
    'column': df_food.columns,
    'dtype': df_food.dtypes.values,
    'non_null_count': df_food.notna().sum().values,
})

                          column    dtype  non_null_count
0                            GPA   object             123
1                         Gender    int64             125
2                      breakfast    int64             125
3               calories_chicken    int64             125
4                   calories_day  float64             106
5                 calories_scone  float64             124
6                         coffee    int64             125
7                   comfort_food   object             124
8           comfort_food_reasons   object             123
9     comfort_food_reasons_coded  float64             106
10                          cook  float64             122
11  comfort_food_reasons_coded.1    int64             125
12                       cuisine  float64             108
13                  diet_current   object             124
14            diet_current_coded    int64             125
15                         drink  float64             123
16                eating_changes   object             122
17          eating_changes_coded    int64             125
18         eating_changes_coded1    int64             125
19                    eating_out    int64             125
20                    employment  float64             116
21                   ethnic_food    int64             125
22                      exercise  float64             112
23              father_education  float64             124
24             father_profession   object             122
25                   fav_cuisine   object             123
26             fav_cuisine_coded    int64             125
27                      fav_food  float64             123
28                food_childhood   object             124
29                         fries    int64             125
30                     fruit_day    int64             125
31                   grade_level    int64             125
32                    greek_food    int64             125
33               healthy_feeling    int64             125
34                  healthy_meal   object             124
35                    ideal_diet   object             124
36              ideal_diet_coded    int64             125
37                        income  float64             124
38                   indian_food    int64             125
39                  italian_food    int64             125
40                life_rewarding  float64             124
41                marital_status  float64             124
42           meals_dinner_friend   object             122
43              mother_education  float64             122
44             mother_profession   object             123
45             nutritional_check    int64             125
46                 on_off_campus  float64             124
47                  parents_cook    int64             125
48                  pay_meal_out    int64             125
49                  persian_food  float64             124
50        self_perception_weight  float64             124
51                          soup  float64             124
52                        sports  float64             123
53                     thai_food    int64             125
54             tortilla_calories  float64             124
55               turkey_calories    int64             125
56                   type_sports   object              99
57                   veggies_day    int64             125
58                      vitamins    int64             125
59               waffle_calories    int64             125
60                        weight   object             123

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns? (Assign the result to a new variable, `df_food_col_subset`.)

In [8]:
# Remove ‘em.
df_food_col_subset = df_food[['calories_day', 'weight', 'Gender']].copy()
df_food_col_subset.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

In [9]:
# Is there a second way to remove columns?
df_food_col_subset_2 = df_food.drop(columns=df_food.columns.difference(['calories_day', 'weight', 'Gender']))
df_food_col_subset_2.head()

   Gender  calories_day                    weight
0       2           NaN                       187
1       1           3.0                       155
2       1           4.0  I'm not answering this.
3       1           3.0             Not sure, 240
4       1           2.0                       190

In [10]:
# 🚀 Extra credit: What about a third way to remove columns?
df_food_col_subset_3 = df_food.loc[:, ['calories_day', 'weight', 'Gender']]
df_food_col_subset_3.head()

   calories_day                    weight  Gender
0           NaN                       187       2
1           3.0                       155       1
2           4.0  I'm not answering this.        1
3           3.0             Not sure, 240       1
4           2.0                       190       1

What about `NaN`s? How many are there?

In [11]:
# Count ‘em.
df_food_col_subset.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

In [12]:
# 🚀 Extra credit: Try to display the NaN sums as a nice pandas DataFrame.
df_food_col_subset.isna().sum().to_frame(name='nan_count')

              nan_count
calories_day         19
weight                2
Gender                0

In [13]:
# 🚀 Extra credit: You can turn one line of code into multiple lines of code using a backslash as a continuation character to break up what would otherwise be a long line.
df_food_col_subset     .isna()     .sum()     .to_frame(name='nan_count')     .rename_axis('column')

              nan_count
column
calories_day         19
weight                2
Gender                0

We gotta remove those `NaN`s―the entire row.

In [14]:
# Drop ‘em in-place.
df_food_col_subset.dropna(inplace=True)
df_food_col_subset.isna().sum()

calories_day    0
weight          0
Gender          0
dtype: int64

In [15]:
# 🚀 Extra credit: Check if the in-place modifications also affected the original DataFrame, df_food. 🙂
# df_food_col_subset was made with .copy(), so df_food keeps its rows and NaNs.
print(df_food.shape, df_food_col_subset.shape)
df_food[['calories_day', 'weight', 'Gender']].isna().sum()

(125, 61) (104, 3)

calories_day    19
weight           2
Gender           0
dtype: int64

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [16]:
# Fix that in-place.
# `weight` is an object column because of values like "I'm not answering this." and "144 lbs".
# Non-numeric values become NaN, then those rows are dropped.
df_food_col_subset['weight'] = pd.to_numeric(df_food_col_subset['weight'], errors='coerce')
df_food_col_subset.dropna(inplace=True)
df_food_col_subset.dtypes

calories_day    float64
weight          float64
Gender            int64
dtype: object

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [17]:
# Savey save!
food_clean_path = 'data/food_coded_clean.csv'
df_food_col_subset.to_csv(food_clean_path, index=False)

In [18]:
# 🚀 Extra credit: Load and print a few lines of the saved file as plain text.
with open(food_clean_path) as f:
    for _ in range(5):
        print(f.readline(), end='')

calories_day,weight,Gender
3.0,155.0,1
2.0,190.0,1
3.0,190.0,1
3.0,180.0,2

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

Load the Ask A Manager Salary Survey 2021 (Responses) data set into a new variable, `df_salary`.

In [19]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set.
salary_data_set_path = 'data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv'

df_salary = pd.read_csv(salary_data_set_path, sep='	')

Was that hard? 🙃

### Explore

You know the drill.

How much data did you just load?

In [20]:
# Count by hand. I’m dead serious.
df_salary.shape

(28227, 18)

What are the columns and their types?

In [21]:
# Show the column names and their types.
df_salary.dtypes

Timestamp                                                                                                                                                                                                                                object
How old are you?                                                                                                                                                                                                                         object
What industry do you work in?                                                                                                                                                                                                            object
Job title                                                                                                                                                                                                                                object
If your job title needs additional context, please clarify here:                                                                                                                                                                         object
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)     object
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                             object
If "Other," please indicate the currency here:                                                                                                                                                                                           object
If your income needs additional context, please provide it here:                                                                                                                                                                         object
What country do you work in?                                                                                                                                                                                                             object
If you're in the U.S., what state do you work in?                                                                                                                                                                                        object
What city do you work in?                                                                                                                                                                                                                object
How many years of professional work experience do you have overall?                                                                                                                                                                      object
How many years of professional work experience do you have in your field?                                                                                                                                                                object
What is your highest level of education completed?                                                                                                                                                                                       object
What is your gender?                                                                                                                                                                                                                     object
What is your race? (Choose all that apply.)                                                                                                                                                                                              object
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [22]:
# Rename ‘em in-place.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race
df_salary.rename(columns=dict(zip(df_salary.columns, [
    'timestamp', 'age', 'industry', 'title', 'title_context', 'salary',
    'additional_compensation', 'currency', 'other_currency', 'salary_context',
    'country', 'state', 'city', 'total_yoe', 'field_yoe',
    'highest_education_completed', 'gender', 'race',
])), inplace=True)
df_salary.dtypes

timestamp                       object
age                             object
industry                        object
title                           object
title_context                   object
salary                          object
additional_compensation        float64
currency                        object
other_currency                  object
salary_context                  object
country                         object
state                           object
city                            object
total_yoe                       object
field_yoe                       object
highest_education_completed     object
gender                          object
race                            object
dtype: object

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [23]:
# List the unique industries and a count of their instances.
df_salary['industry'].value_counts()

industry
Computing or Tech                       4726
Education (Higher Education)            2481
Nonprofits                              2421
Health care                             1905
Government and Public Administration    1894
                                        ...
Real Estate Investment Support             1
Government relations                       1
Household Services                         1
Academic publishing                        1
study                                      1
Name: count, Length: 1225, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new variable, `df_salary_tech`.

In [24]:
# Filtery filter.
df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech'].copy()

Do a sanity check by counting.

In [25]:
# Sanity check count.
print(len(df_salary_tech))
df_salary_tech['industry'].value_counts()

4726

industry
Computing or Tech    4726
Name: count, dtype: int64

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [26]:
# Filtery filter (in place) for just the jobs that pay in USD!
df_salary_tech.drop(df_salary_tech[df_salary_tech['currency'] != 'USD'].index, inplace=True)
df_salary_tech['currency'].value_counts()

currency
USD    3792
Name: count, dtype: int64

What we really want know is how each U.S. state pays in tech. What value in `country` represents the United States of America?

In [27]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_tech['country'].value_counts()

country
United States                1580
USA                          1227
US                            413
U.S.                          109
United States of America       91
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                             10
U.S.A.                          7
United States of America        7
Israel                          5
Canada                          4
UnitedStates                    2
New Zealand                     2
united States                   2
United Kingdom                  2
Brazil                          2
France                          2
U.S.A                           2
United States of america        2
United States Of America        2
Usa                             2
U.S                             2
India                           2
Poland                          2
Spain                           2
United State of America         2
Australia                       2
U.S.                            2
Unite States                    2
International                   1
Unites States                   1
United STates                   1
Japan                           1
US                              1
United Stares                   1
Australian                      1
Denmark                         1
Jamaica                         1
U.S.A                           1
Thailand                        1
San Francisco                   1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Hong KongKong                   1
Romania                         1
Netherlands                     1
China                           1
Mexico                          1
United Stated                   1
Danmark                         1
Cuba                            1
Remote (philippines)            1
Singapore                       1
United State                    1
Uruguay                         1
 US                             1
U.s.                            1
Italy                           1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Pakistan                        1
Puerto Rico                     1
America                         1
Uniyed states                   1
Ecuador                         1
Name: count, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [28]:
# Replace them all in-place with 'US'.
top_5_countries = df_salary_tech['country'].value_counts().index[:5]
print(list(top_5_countries))
df_salary_tech['country'] = df_salary_tech['country'].replace(list(top_5_countries), 'US')

['United States', 'USA', 'US', 'U.S.', 'United States of America']

Have a look at the count of each unique country again now.

In [29]:
# Count again.
df_salary_tech['country'].value_counts()

country
US                           3420
United States                  68
Usa                            59
USA                            56
usa                            28
United states                  23
united states                  14
Us                             12
us                             10
United States of America        7
U.S.A.                          7
Israel                          5
Canada                          4
Usa                             2
U.S.A                           2
U.S                             2
Brazil                          2
India                           2
UnitedStates                    2
United States of america        2
United Kingdom                  2
Unite States                    2
Australia                       2
Spain                           2
united States                   2
New Zealand                     2
Poland                          2
United State of America         2
France                          2
U.S.                            2
United States Of America        2
United Stares                   1
Japan                           1
United STates                   1
Romania                         1
Unites States                   1
Australian                      1
Denmark                         1
Jamaica                         1
China                           1
Thailand                        1
U.S.A                           1
Colombia                        1
denmark                         1
Ghana                           1
Nigeria                         1
ss                              1
Nigeria                         1
Burma                           1
Hong KongKong                   1
San Francisco                   1
Uruguay                         1
Netherlands                     1
Pakistan                        1
US                              1
Uniyed states                   1
America                         1
Puerto Rico                     1
U.s.                            1
 US                             1
United State                    1
Cuba                            1
Danmark                         1
Italy                           1
International                   1
United Stated                   1
Remote (philippines)            1
Singapore                       1
Mexico                          1
Canada                          1
United Stateds                  1
ISA                             1
singapore                       1
Ecuador                         1
Name: count, dtype: int64

Did you notice anything interesting?

In [30]:
# 🚀 Extra credit: Resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.
# Lowercase and strip everything that isn't a letter, so "U.S.A. ", "usa", "United states" etc. collapse together.
us_variants = {'us', 'usa', 'unitedstates', 'unitedstatesofamerica'}
country_key = df_salary_tech['country'].str.lower().str.replace(r'[^a-z]', '', regex=True)
df_salary_tech.loc[country_key.isin(us_variants), 'country'] = "US"

In [31]:

# 🚀 Extra credit: If you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.
df_salary_tech['country'].value_counts()

country
US                         3725
Israel                        5
Canada                        4
Poland                        2
New Zealand                   2
United State of America       2
United Kingdom                2
Brazil                        2
Spain                         2
India                         2
France                        2
Unite States                  2
Australia                     2
denmark                       1
Hong KongKong                 1
Burma                         1
San Francisco                 1
Romania                       1
Nigeria                       1
Japan                         1
United Stares                 1
Australian                    1
Colombia                      1
ss                            1
Denmark                       1
Jamaica                       1
Unites States                 1
China                         1
Nigeria                       1
Ghana                         1
Thailand                      1
ISA                           1
Netherlands                   1
International                 1
Uniyed states                 1
America                       1
Puerto Rico                   1
United State                  1
Cuba                          1
Danmark                       1
Italy                         1
United Stated                 1
Pakistan                      1
Remote (philippines)          1
Singapore                     1
Uruguay                       1
Mexico                        1
Canada                        1
United Stateds                1
singapore                     1
Ecuador                       1
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [32]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.
try:
    display(df_salary_tech[df_salary_tech['country'] == 'US'] \
        .groupby('state')['salary'] \
        .agg(['min', 'mean', 'max']) \
        .sort_values('mean', ascending=False))
except TypeError as e:
    print('TypeError:', e)

TypeError: agg function failed [how->mean,dtype->object]

 Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed. 🤔

In [33]:
# Fix it in-place.
# Salaries are strings like "55,000", so remove the commas and convert to numbers.
df_salary_tech['salary'] = pd.to_numeric(df_salary_tech['salary'].str.replace(',', ''), errors='coerce')
df_salary_tech.dropna(subset=['salary'], inplace=True)
df_salary_tech['salary'].dtype

dtype('int64')

Let’s try that again.

In [34]:
# Try it again. Yeah!
df_salary_tech[df_salary_tech['country'] == 'US'] \
    .groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Florida                          28800  157457.232143  2600000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155140.708841   875000
Washington                          72  151685.435294   950000
New York                         14000  147836.300860   590000
New Jersey, New York            135000  137500.000000   140000
Nevada                           38000  136645.454545   425000
Massachusetts                    37000  135018.880795  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119268.242604   315000
Louisiana, Washington           117000  117000.000000   117000
Maryland                         51260  116992.145455   205000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Tennessee                        36550  112847.058824   240000
Georgia                            500  112719.081395   250000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  106752.793103   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
North Carolina                   29000  105035.441441   260000
New York, Texas                 105000  105000.000000   105000
Massachusetts, New Hampshire    105000  105000.000000   105000
Arizona                          35000  104491.891892   210000
Rhode Island                     56160  103587.142857   180000
Maine                            50000  103571.428571   173000
South Carolina                   40000  102111.111111   205000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Michigan                         15000   95750.803571   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Alabama                          29120   92510.000000   350000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [35]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_tech['timestamp'] = pd.to_datetime(df_salary_tech['timestamp'], format='%m/%d/%Y %H:%M:%S')
df_salary_tech_2021_2023 = df_salary_tech[df_salary_tech['timestamp'].dt.year.isin([2021, 2022, 2023])]

df_salary_tech_2021_2023[df_salary_tech_2021_2023['country'] == 'US'] \
    .groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values('mean', ascending=False)

                                   min           mean      max
state
Michigan, Texas, Washington     340000  340000.000000   340000
California, Oregon              200000  200000.000000   200000
California, Colorado            176000  176000.000000   176000
Georgia, Massachusetts          175000  175000.000000   175000
Alabama, District of Columbia   156000  156000.000000   156000
California                           0  155355.206422   875000
Washington                          72  151458.278107   950000
New York                         14000  148157.669540   590000
Nevada                           38000  141310.000000   425000
New Jersey, New York            135000  137500.000000   140000
Massachusetts                    37000  134989.043189  1650000
District of Columbia             10000  132318.036364   267500
New Mexico                       70000  132200.000000   300000
Utah, Vermont                   130000  130000.000000   130000
New Jersey                       40000  128802.475000   603000
Connecticut                      62400  128375.000000   270000
Virginia                         43642  127370.512821   450000
Colorado                         45000  127048.895833   630000
Massachusetts, Rhode Island     125000  125000.000000   125000
Oregon                           16200  124297.800000   320000
Georgia, Washington             123000  123000.000000   123000
West Virginia                   116500  120500.000000   125000
Illinois                         13500  119621.029762   315000
Georgia                          29120  118004.262500   250000
Maryland                         51260  117862.370370   205000
Louisiana, Washington           117000  117000.000000   117000
Delaware                         63000  116600.000000   169000
South Dakota                     86000  115333.333333   150000
Wisconsin                            1  114268.000000   920000
Texas                            10700  113909.713004   280000
Florida                          28800  113047.363636   400000
Tennessee                        36550  112847.058824   240000
Alaska                           67000  112500.000000   158000
Vermont                          65000  111781.250000   200000
Pennsylvania                     32000  111623.123894   237000
Idaho                            50000  111527.692308   312000
Rhode Island                     76000  111491.666667   180000
South Carolina                   40000  109875.000000   205000
District of Columbia, Virginia  109200  109200.000000   109200
Minnesota                        34000  107063.872093   230000
Ohio                             32240  106338.835821   954000
Utah                             33280  105836.479167   245000
Massachusetts, New Hampshire    105000  105000.000000   105000
New York, Texas                 105000  105000.000000   105000
North Carolina                   29000  104944.854545   260000
Arizona                          35000  104491.891892   210000
Maine                            50000  103571.428571   173000
Iowa                             47840   99729.736842   160000
Kansas                           41500   99565.052632   167000
North Dakota                     45760   97880.000000   150000
Alabama                          29120   97738.181818   350000
Michigan                         36800   97723.055556   235000
Montana                          65000   95500.000000   145000
Missouri                            80   95317.652174   200000
Arizona, Utah                    95000   95000.000000    95000
Mississippi                      94000   94000.000000    94000
New Hampshire                       55   93003.437500   193000
Kentucky                         39000   92375.000000   170000
Nebraska                         43000   90975.294118   166400
Indiana                          15000   88566.647059   200000
Oklahoma                         28536   87929.500000   180000
Massachusetts, Pennsylvania      83000   83000.000000    83000
Arkansas                         55000   81682.300000   144000
California, Maryland             81500   81500.000000    81500
Louisiana                        35360   76596.000000   110000
Alabama, Montana                 72000   72000.000000    72000

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

In [36]:
# Same cleaning steps as before, on a copy of df_salary, without the industry filter.
df_salary_all = df_salary[df_salary['currency'] == 'USD'].copy()

country_key = df_salary_all['country'].str.lower().str.replace(r'[^a-z]', '', regex=True)
df_salary_all.loc[country_key.isin(us_variants), 'country'] = 'US'
df_salary_all = df_salary_all[df_salary_all['country'] == 'US'].copy()

df_salary_all['salary'] = pd.to_numeric(df_salary_all['salary'].str.replace(',', ''), errors='coerce')
df_salary_all.dropna(subset=['salary', 'state'], inplace=True)

salary_by_state = df_salary_all \
    .groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values('mean', ascending=False)
salary_by_state

,min,mean,max
state,,,
"Michigan, Texas, Washington",340000,340000.000000,340000
"Indiana, Ohio",245000,245000.000000,245000
Alaska,27040,232275.078125,10000000
"Colorado, Nevada",190000,190000.000000,190000
"California, Montana",185000,185000.000000,185000
...,...,...,...
"District of Columbia, Washington",35000,35000.000000,35000
"Alabama, California",29120,29120.000000,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,27040.000000,27040
"Michigan, South Carolina",0,25666.500000,51333
"Maryland, New York",14000,14000.000000,14000

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

In [37]:
# Styling only changes how the table is displayed, not the values.
df_salary_before = df_salary.copy()

display(salary_by_state.style.format('${:,.2f}'))

print('df_salary unchanged:', df_salary.equals(df_salary_before))

df_salary unchanged: True

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

In [38]:
# Multi-state answers are joined with ", ", so keep only rows without a comma.
df_salary_single_state = df_salary_all[~df_salary_all['state'].str.contains(',')]

salary_by_single_state = df_salary_single_state \
    .groupby('state')['salary'] \
    .agg(['min', 'mean', 'max']) \
    .sort_values('mean', ascending=False)
salary_by_single_state.style.format('${:,.2f}')

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)

In [39]:
quantiles = [0, 0.05, 0.25, 0.5, 0.75, 0.95, 1]

salary_quantiles = df_salary_single_state \
    .groupby('state')['salary'] \
    .quantile(quantiles) \
    .unstack()
salary_quantiles.columns = [f'{q:.0%}' for q in quantiles]
salary_quantiles.insert(0, 'count', df_salary_single_state.groupby('state').size())
salary_quantiles = salary_quantiles.sort_values('50%', ascending=False)

# The count column isn't money, so format only the quantile columns.
salary_quantiles.style.format('${:,.2f}', subset=salary_quantiles.columns[1:])